### ISSUE TITLE
invalid value

### ISSUE THREAD

**Issue by codedigger123** [helium/gateway-mfr-rs#32]
I try the command  gateway_mfr --device "ecc://i2c-5:96?slot=0" test, but it fail as following:
error: invalid value 'ecc://i2c-5:96?slot=0' for '--device <DEVICE>': invalid device url "ecc://i2c-5:96?slot=0"
I have verify that i2c bus,address,slot is OK,but why output fail?

**Comment by madninja** [comment]
The default binaryis currently being built without any features.. If you had built it with `--features "ecc608"` this would have worked. 

I've added ecc608 as a default feature in #33 so that this will work out of the box going forward without needing to build with a feature flag. Thank you for reporting
