### ISSUE TITLE
gateway_mfr can't run in a mipsel platform

### ISSUE THREAD

**Issue by Bei-Ji-Quan** [helium/gateway-mfr-rs#7]
hi,
I build the gateway_mfr with "cross build --target mipsel-unknown-linux-musl --release",but it can not run on MT688(when i run ./gateway_mfr,  it shows "-ash: ./gateway_mfr: not found"). But I build the gateway_rs with the same steps, it works.

**Comment by madninja** [comment]
And you are sure that gateway_mfr was actually copied to the device? It seems it just can't find the executable at all

**Comment by Bei-Ji-Quan** [comment]
yes, I checked the size.
I also build an aarch64-unknown-linux-musl release with another board, it also works. It really puzzles me.

**Comment by Bei-Ji-Quan** [comment]
could you build a release for mipsel ?

**Comment by madninja** [comment]
Fixed with #9 

See the [releases](https://github.com/helium/gateway-mfr-rs/releases) page for tagged releases with target architecture builds for various cross compile targets

**Comment by madninja** [comment]
@Bei-Ji-Quan please confirm that this works for you.

**Comment by lblmine88** [comment]
Hi, I got the same issue with the latest release 0.2.0, my platform is MT7628 with Openwrt 15.05 uclibc which is not musl.
not sure if related.

**Comment by madninja** [comment]
> Hi, I got the same issue with the latest release 0.2.0, my platform is MT7628 with Openwrt 15.05 uclibc which is not musl.
> not sure if related.

I have no idea if this is related or not but it doesn't appear to be.. 

1. You're talking about a different target
2. You didn't specify what the error is
3. musl should help since it's doesn't require system linked libraries

I would suggest you get more details on the actual platform and error and open a new ticket? Feel free to refer to this one if it's actually related
